config/routes.rb
Rails.application.routes.draw do
  #get 'pages/home'
  root 'pages#home'
  get 'about'=> 'pages#about'
  get 'prueba'=> 'pages#prueba'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def prueba
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miaplicacion</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Inicio", root_path %>
    <%= link_to "Nosotros", about_path %>
    <%= link_to "Prueba", prueba_path %>
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Acerca de nosotros</h1>
<p>Estamos trabajando en la aplicación de pinterest hecha por Rails</p>

app/views/pages/home.html.erb
<h1>Bienvenido a mi Aplicación</h1>
<p>Registrate <%= link_to "aquí", "#"%></p>

app/views/pages/prueba.html.erb
<h1>Esto es una Prueba</h1>
<p>No se alarme esto es una prueba no más</p>